version: '3.9'
# This version indicates the Compose file syntax version and feature support.
# Check the Docker documentation for the latest Compose file version for your project.

services:
  redis:
    image: redis:alpine3.19
    # Specify the Redis Docker image using Alpine 3.19 as a base for a lightweight footprint.
    container_name: redis-container
    # Define a custom name for the container.
    ports:
      - "6379:6379"
      # Expose Redis port 6379 to the host for external access.
    networks:
      - backend
      # Connect the Redis service to the backend network.

  mongo:
    image: mongo:7.0.9
    # Specify the MongoDB Docker image.
    container_name: mongo-container
    # Define a custom name for the container.
    ports:
      - "27017:27017"
      # Expose MongoDB port 27017 to the host for external access.
    networks:
      - backend
      # Connect the MongoDB service to the backend network.

  node:
    image: node:22.1.0-alpine3.18
    # Specify the Node.js Docker image using version 22.1.0 with an Alpine 3.18 base for a lightweight footprint.
    container_name: node-container
    # Define a custom name for the container.
    working_dir: /app
    # Set the working directory inside the container to /app.
    networks:
      - frontend
      # Connect the Node.js service to the frontend network.
    volumes:
      - ./app:/app
      # Mount the local app directory to the /app directory in the container for persistent storage.

  azure_cli:
    image: mcr.microsoft.com/azure-cli:2.9.1
    # Specify the Azure CLI Docker image version 2.9.1.
    container_name: azure-cli-container
    # Define a custom name for the container.
    networks:
      - frontend
      # Connect the Azure CLI service to the frontend network.

# Define the networks used by the services.
networks:
  frontend:
    # This network connects the Node.js and Azure CLI services.
    driver: bridge
    # Use the default bridge network driver.

  backend:
    # This network connects the Redis and MongoDB services.
    driver: bridge
    # Use the default bridge network driver.
